import './globals.css'
import { Inter } from 'next/font/google'
import Cabecalho from './componets/cabecalho/cabecalho'
import Rodape from './componets/rodape/Rodape'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Entrega next 4',
  description: 'Generated by create rm551061',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
      <Cabecalho/>
        {children}
      <Rodape/>  </body>
    </html>
  )
}
